
import React from 'react';
import {
  Plus, Link as LinkIcon, Calendar, Clock, Users, Workflow,
  Grid, BarChart2, Settings, HelpCircle, ExternalLink,
  MoreVertical, Copy, Search, ChevronDown, MessageSquare,
  Sparkles, User, Command, LayoutDashboard, Zap, Share2, Check,
  ChevronLeft, ChevronRight, Globe, Phone, Trash2, Video, CalendarDays, X, MapPin, ArrowLeft,
  Mail, Upload, Filter, Send, AlertTriangle, Trophy, Thermometer, History,
  FileText, DownloadCloud, Table, UploadCloud, Info, Loader2,
  Building, UserCheck, CheckSquare, Edit, RefreshCw, Bell, Code, Save, AlertCircle, Eye,
  Bold, Italic, Underline, List, ListOrdered, AlignLeft, AlignCenter, AlignRight, Image,
  // New icons for multichannel
  MessageCircle, Smartphone, CheckCircle, XCircle, MousePointer,
  CheckCheck, Award, XOctagon, UserMinus, Circle, ChevronUp, Lock
} from 'lucide-react';


// Define a type for icon props if not already defined elsewhere
interface IconProps extends React.SVGProps<SVGSVGElement> {
  size?: number;
  strokeWidth?: number;
}

export const Icons = {
  Plus,
  Link: LinkIcon,
  Calendar,
  Clock,
  Users,
  Workflow,
  Globe,
  Grid,
  BarChart2,
  Settings,
  HelpCircle,
  ExternalLink,
  MoreVertical,
  Copy,
  Search,
  ChevronDown,
  MessageSquare,
  Sparkles,
  User,
  Command,
  LayoutDashboard,
  Zap,
  Share2,
  Check,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  Phone,
  Trash2,
  Video,
  CalendarDays,
  X,
  MapPin,
  Mail,
  Upload,
  Filter,
  Send,
  AlertTriangle,
  Trophy,
  Thermometer,
  History,
  FileText,
  DownloadCloud,
  Table,
  UploadCloud,
  Info,
  Loader2,
  Building,
  UserCheck,
  CheckSquare,
  Edit,
  RefreshCw,
  Bell,
  Code,
  Save,
  AlertCircle,
  Eye,
  Bold,
  Italic,
  Underline,
  List,
  ListOrdered,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Image,
  // New icons for multichannel
  MessageCircle,
  Smartphone,
  CheckCircle,
  XCircle,
  MousePointer,
  CheckCheck,
  Award,
  XOctagon,
  UserMinus,
  Circle,
  ChevronUp,
  Lock
};